// Base Key Layout Source|Keyboard|81050
namespace VRTK
{
    using UnityEngine;
    using KeyboardLayout = VRTK_KeyboardLayout;

    /// <summary>
    /// This abstract class is the base for all key layout sources
    /// </summary>
    /// <remarks>
    /// A key layout source is responsible for providing a `VRTK_KeyboardLayout` to calculators
    /// and/or renderers on the same game object. A key layout may come from a serialized
    /// `VRTK_KeyboardLayout` or be generated from some other source such as an XML file
    /// describing an on-screen keyboard layout.
    /// </remarks>
    public abstract class VRTK_BaseKeyLayoutSource : MonoBehaviour
    {
        /// <summary>
        /// Return the `VRTK_KeyboardLayout` that belongs to or is generated by this key layout source
        /// </summary>
        /// <returns>The key layout</returns>
        public abstract KeyboardLayout GetKeyLayout();
    }
}