// Renderable Key Layout|Keyboard|81025
namespace VRTK
{
    using UnityEngine;
    using KeyClass = VRTK_Keyboard.KeyClass;
    using IKey = VRTK_Keyboard.IKey;
    using System;

    /// <summary>
    /// A meta keyboard layout with calculated key rectangles
    /// </summary>
    /// <remarks>
    /// Renderable Key Layouts are generated by a Key Layout Calculator usually based off of a Keyboard Layout.
    /// 
    /// A RenderableKeyLayout contains:
    /// - Per-key metadata base off KeyboardLayout
    /// - Calculated positions and dimensions for each key within key area containers
    /// </remarks>
    public class VRTK_RenderableKeyLayout
    {
        /// <summary>
        /// A renderable keyset
        /// </summary>
        public class Keyset
        {
            /// <summary>
            /// The name of this keyset
            /// </summary>
            public string name;
            /// <summary>
            /// The areas that belong to this keyset
            /// </summary>
            public KeyArea[] areas;

            public override string ToString()
            {
                return VRTK_DebugHelpers.ObjectDebugString("Keyset", new string[]
                {
                    VRTK_DebugHelpers.PropertyDebugString("name", name),
                    VRTK_DebugHelpers.ArrayPropertyDebugString("areas", areas),
                });
            }
        }

        /// <summary>
        /// A renderable key area
        /// </summary>
        public class KeyArea
        {
            /// <summary>
            /// The name of this key area
            /// </summary>
            public string name;
            /// <summary>
            /// The rect this key area is placed in
            /// </summary>
            public Rect rect;
            /// <summary>
            /// The keys that belong to this key area
            /// </summary>
            public Key[] keys;
            
            public override string ToString()
            {
                return VRTK_DebugHelpers.ObjectDebugString("KeyArea", new string[]
                {
                    VRTK_DebugHelpers.PropertyDebugString("rect", rect),
                    VRTK_DebugHelpers.ArrayPropertyDebugString("keys", keys),
                });
            }
        }

        /// <summary>
        /// A renderable key
        /// </summary>
        public class Key : IKey
        {
            /// <summary>
            /// The preferred GameObject name for this key
            /// </summary>
            public string name;
            /// <summary>
            /// The button text for this key
            /// </summary>
            public string label;
            /// <summary>
            /// The rect this key is placed in
            /// </summary>
            public Rect rect;
            /// <summary>
            /// The class of this key
            /// </summary>
            public KeyClass keyClass;
            /// <summary>
            /// The character to type (for keyClass = Character)
            /// </summary>
            public char character;
            /// <summary>
            /// The keyset to switch to (for keyClass = KeysetModifier)
            /// </summary>
            public int keyset;

            public bool isSpecial
            {
                get { return keyClass != KeyClass.Character; }
            }

            public override string ToString()
            {
                return VRTK_DebugHelpers.ObjectDebugString("Key", new string[]
                {
                    VRTK_DebugHelpers.PropertyDebugString("rect", rect),
                });
            }

            public KeyClass GetKeyClass()
            {
                return keyClass;
            }

            public char GetCharacter()
            {
                return character;
            }

            public int GetKeyset()
            {
                return keyset;
            }
        }

        /// <summary>
        /// The keysets that belong to this renderable key layout
        /// </summary>
        public Keyset[] keysets;

        public override string ToString()
        {
            return VRTK_DebugHelpers.ObjectDebugString("VRTK_RenderableKeyLayout", new string[]
            {
                VRTK_DebugHelpers.ArrayPropertyDebugString("keysets", keysets),
            });
        }
    }
}